<a href="https://colab.research.google.com/github/venkatacrc/Notes/blob/master/Coding/SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SQL

Source: [SQL for Data Science](https://www.coursera.org/learn/sql-for-data-science/)

SQL is a standard computer language for relational database management and data manipulation. Used to read/query data, insert new data, update/modify data.

SQL is a non-procedural language and cannot write complete applications.

###Relational Database Management Systems
* Microsoft SQL Server
* IBM DB2 
* Oracle
* Sybase ASE
* PostgreSQL
* MySQL
* Apache Open Office Base
* SQLite

##Data Models

Think Before You Code

What is the problem you are trying to solve?

Understand your data

* Understand the business process or subject matter the data is modeled after
* Know the business rules
* Understand how your data is organized and structured in the table(modeled)

Why This is Worthwhile
* Get more accurate results
* Speed up your work
* Have less rework

**Data Modeling**
Organizes and structures information into multiple, replated tables. Can represent a business process or show replationships between business processes. Should closely represent real world.

Evolution of Data Models

Hierarchical (1960) $\rightarrow$ Network (1969) $\rightarrow$ Relational (1970) $\rightarrow$ Entity Relationship (1976) $\rightarrow$ Semantic (1978) $\rightarrow$ Object-Oriented (1985) $\rightarrow$ Extended Relational (1990) $\rightarrow$ NoSql (2009)

NoSQL - Not Only SQL - A mechanism for storage and retrieval of unstructured data modeled by means other than tabular relations in relational databases.

###Data Model Building Blocks

####Entity:
Person, place, thing, or event distinguishable, unique, and distinct
####Attribute:
A characteristic of an entity
####Relationship:
Describes one-to-many(customer to invoices), many-to-many(students to classes), and one-to-one(manager to store) association among entities
###ER Diagrams
Show relationships, business process, represented visually using links(primary keys).
####Primary Key
A column (or set of columns) whose values uniquely identify every row in a table
####Foreign Key
One or more columns that can be used together to identify a single row in another table

###ER Diagram Notation
* Chen Notation (1:M, M:N, 1:1)
* Crow's Foot Notation (||,Crow's foot)
* UML Class Diagram Notation (1.1 1.*)

####SELECT
```
SELECT prod_name, prod_id, prod_price
FROM Products
LIMIT 5 ;#number_of_records
```

Use wildcard to retrieve mulitple columns

####Creating new tables
* Use tables to make models and predictions
* Create dashboards
* Visualize data with other tools
* Extract data from other sources

Primary keys must have a value
```
CREATE TABLE Shoes
(
  Id      char(10)     PRIMARY_KEY,
  Brand   char(10)     NOT NULL,
  Type    char(250)    NOT NULL,
  Price   decimal(8,2) NOT NULL,
  Desc    Varchar(750) NULL
);
```
**Adding Data to the Table**

```
INSERT INTO Shoes
VALUES('14674892', 'Gucci', 'Slippers', '695.00', NULL);
```
Better to be more specific
```
INSERT INTO Shoes
(Id, Brand, Type, Price, Desc)
VALUES
('14674892', 'Gucci', 'Slippers', '695.00', NULL);
```

####Creating temporary tables
* will be deleted when current session is terminated
* faster than creating a real table
* useful for complex queries using subsets and joins

```
CREATE TEMPORARY TABLE Sandals AS
(
  SELECT *
  FROM Shoes
  WHERE shoe_type = 'sandals'
)
```
####Adding Comments to SQL
Single Line
```
SELECT shoe_id
--, brand_id
, shoe_name
from Shoes
```

```
SELECT shoe_id
/*, brand_id
, shoe_name
*/
from Shoes
```

* References
  * What is SQL and How is it Used?
  * NTC Hosting: Structured Query Language (it's worth exploring this site, not just this singular posting)
  * SQLite Tutorial
  * Norwalk Aberdeen: Entity-Relationsip Diagrams (9 Minute YouTube Video)
  * Star Schema vs. Snowflake Schema
  * Explain Star Schema & Snow Flake Design (5 Minute YouTube Video)
  * Data Modeling 101
  * What is Data Modeling - An Introduction for Business Analysts
  * Wikipedia: Data Modeling